name: terrform aws task

 

on:
  push:
    branches:
      - main

 

jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY : ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: pull code
        uses: actions/checkout@v6.0.2
      - name: install terraform
        uses: hashicorp/setup-terraform@v2.0.3
      - name: Terraform init
        run: terraform init
      - name: terraform plan
        run: terraform plan
      - name: terraform apply
        run: terraform apply -auto-approve
